# Generated by Django 4.1.3 on 2023-05-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='customer',
        ),
    ]
