# Generated by Django 4.1.3 on 2023-05-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentmodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='customer',
        ),
    ]
