# Generated by Django 4.2 on 2023-04-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initiatepaymentsystem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiatepaymentsystem',
            name='user',
        ),
    ]
